### ISSUE TITLE
Is INFURA id needed or not for BSC?

### ISSUE THREAD

**Issue by php4fan** [kaiesh/connect-web3-wallets#1]
First of all thank you so much for this much-needed repository, it's really amazing (and it's surprising that nothing like this is provided out-of-the-box by WalletConnect and the other libraries involved - but I digress).

In your stackexchange answer https://ethereum.stackexchange.com/questions/101587/can-i-implement-walletconnect-with-vanilla-javascript you said (actually in a comment within the example code):
> //An infura ID, or custom ETH node is required for Ethereum, for Binance Smart Chain you can just use their public endpoint

but then in `sample.js` there is:
```
KV.set_infuraID(YOUR_INFURA_ID);
```
and I don't see any mention of how to set things up for BSC without that. I tried simply removing that line, but then WalletConnect simply doesn't show up as an option under "connect your wallet" (on mobile, no option shows up at all).

**Comment by kaiesh** [comment]
Oh this is a good point - the logic to display WalletConnect is [incorrect](https://github.com/kaiesh/connect-web3-wallets/blob/4935cc586a4d2d78a161e45d172b05a8c40eabb3/src/KV.js#L108)!

The wallet connection option should continue to be permitted in so long as the chainId is not set to the ETH network(s). So instead the option should be presented, and throw an [error when initialised](https://github.com/kaiesh/connect-web3-wallets/blob/4935cc586a4d2d78a161e45d172b05a8c40eabb3/src/KV.js#L227) to an incompatible network.

I'll make this change and push!

**Comment by kaiesh** [comment]
@php4fan please check out the commit [95fe53](https://github.com/kaiesh/connect-web3-wallets/commit/95fe53bf425717e9e2c499b142a289326cc025aa) and let me know if it does what you were looking for.

**Comment by kaiesh** [comment]
Main branch and CDN updated with patch
